- name: show return value of command module
  hosts: vagrant1
  tasks:
    - name: capture output of the id command
      command: id -un
      register: login
    - debug: msg="Logged in as user {{ login.stdout }}" 
    - name: Run myprog
      command: /opt/myprog
      register: result
      ignore_errors: True
    - debug: var=result


- name: print out operating system
  hosts: all
  gather_facts: True
  tasks: 
    - debug: var=ansible_distribution


